# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1eea3ee231909c9e6a5f5dfb4209beb541bea2a64ecd96017ed5e37b7a067b49b185835630f7bebb39bf3841d41677f5f62073bd1e3548ba260b6b956e10abb7

test:
  secret_key_base: 1b19589e7e931fc0c49e14565eccbbc0f430da97cef195359009249a00d84911eb4f33eed1fced774185935fb2c29dc3205e0f6843c02ae7d134ff373327d8a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
